### ISSUE TITLE
2.21 11:10腾讯云函数运行不了

### ISSUE THREAD

**Issue by 1325266720** [writemanybug/WPS-invite#1]
ヘ(_ _ヘ)dalao，我用你wps_invite.py直接复制去腾讯云函数运行，没改任何东西都测试失败了
显示{"errorCode":-1,"errorMessage":"Invoking task timed out after 3 seconds","statusCode":433}

**Comment by writemanybug** [comment]
有酷友反馈是我那个被邀请ID加多了，删到10个就好了，然后执行超时时间改为150秒

**Comment by 1325266720** [comment]
> 有酷友反馈是我那个被邀请ID加多了，删到10个就好了，然后执行超时时间改为150秒

完美运行，膜拜dalaoヘ(_ _ヘ)

**Comment by writemanybug** [comment]
问题解决
